chore: make tensor.repeat arguments explicitly int
- Fix instances where tensor was passed as an argument to tensor.repeat by explicitly converting to int. This avoids potential issues.
- This fixes the error:

```
Poe => env MYPYPATH=src mypy --namespace-packages --explicit-package-bases src tests
src/kitsuyui_ml/torch_ext/lcm_cat.py:32: error: No overload variant of "repeat" of "TensorBase" matches argument types "int", "Tensor", "int", "int"  [call-overload]
src/kitsuyui_ml/torch_ext/lcm_cat.py:32: note: Possible overload variants:
src/kitsuyui_ml/torch_ext/lcm_cat.py:32: note:     def repeat(self, repeats: Sequence[int | SymInt]) -> Tensor
src/kitsuyui_ml/torch_ext/lcm_cat.py:32: note:     def repeat(self, *repeats: int | SymInt) -> Tensor
src/kitsuyui_ml/torch_ext/lcm_cat.py:34: error: No overload variant of "repeat" of "TensorBase" matches argument types "Tensor", "int", "int", "int"  [call-overload]
src/kitsuyui_ml/torch_ext/lcm_cat.py:34: note: Possible overload variants:
src/kitsuyui_ml/torch_ext/lcm_cat.py:34: note:     def repeat(self, repeats: Sequence[int | SymInt]) -> Tensor
src/kitsuyui_ml/torch_ext/lcm_cat.py:34: note:     def repeat(self, *repeats: int | SymInt) -> Tensor
```